language: ruby
os:
  - osx
  - linux
script:
  - bin/dotsetup
  - vi --version
  - git --version
  - curl --version
  - fish --version
  - fisher --version
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/460308342559c8c60a12
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
