#!/bin/bash

set -e

script_path=`pwd`/$0
script_relative_path='/dotsetup'
root=${script_path%$script_relative_path};

echo "Dotfiles root: $root"

command_exists () {
  type "$1" &> /dev/null ;
}

if [[ "$OSTYPE" == linux* ]]; then
  sudo apt update
  echo "### Linux specific: Install Git, Vim and ZSH ###"
  sudo apt install -y git vim zsh openssh-server curl fish
fi

if [[ "$OSTYPE" == darwin* ]]; then
  if [[ "$1" == "brew" ]]; then
    echo "### Brew ###"
    command_exists brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    xargs brew install < $root/brew/brew.txt
    if [[ "$2" == "cask" ]]; then
      echo "### Cask ###"
      xargs brew install --cask < $root/brew/cask.txt
    fi
  fi
fi

echo "### Updating dotfiles ###"
git -C $root pull
git -C $root submodule update --init

echo "### Linking configuration ###"
ln -sf $root/zsh/rc.zsh ~/.zshrc
ln -sf $root/zsh/env.zsh ~/.zshenv
ln -sf $root/zsh/zimrc.zsh ~/.zimrc
ln -sf $root/zsh/p10k.zsh ~/.p10k.zsh
mkdir -p ~/.config/fish
ln -sf $root/fish/config.fish ~/.config/fish/config.fish
ln -sf $root/git/unix ~/.gitconfig
ln -sf $root/git ~/.config/git
ln -sf $root/git/ignore ~/.gitignore
ln -sf $root/vimrc ~/.vimrc
mkdir -p $XDG_CONFIG_HOME/nvim
ln -sf $root/vimrc $XDG_CONFIG_HOME/nvim/init.vim
mkdir -p ~/.vim/autoload
ln -sf $root/vendors/vim-plug/plug.vim ~/.vim/autoload/plug.vim
mkdir -p $XDG_DATA_HOME/nvim/site/autoload
ln -sf $root/vendors/vim-plug/plug.vim $XDG_DATA_HOME/nvim/site/autoload/plug.vim
ln -sf $root/ackrc ~/.ackrc
ln -sf $root/tigrc ~/.tigrc
ln -sf $root/conan/Makefile ~/dev/conan/cci/recipes
ln -sf $root/conan/Darwin.txt ~/dev/conan/cci/recipes/Darwin.txt
ln -sf $root/conan/ios.txt ~/dev/conan/cci/recipes/ios.txt
cp $root/conan/gitignore ~/dev/conan/cci/recipes/.gitignore


