#!/bin/bash

set -e

script_path=$(pwd)/$0
script_relative_path='/dotsetup'
root=${script_path%$script_relative_path}

echo "Dotfiles root: $root"

command_exists() {
  type "$1" &>/dev/null
}

if [[ "$OSTYPE" == linux* ]]; then
  sudo apt update
  echo "### Linux specific: Install Git, Neovim and ZSH ###"
  sudo apt install -y git nvim zsh openssh-server curl fish
fi

if [[ "$OSTYPE" == darwin* ]]; then
  if [[ "$1" == "brew" ]]; then
    echo "### Brew ###"
    command_exists brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

    xargs brew install <$root/brew/brew.txt
    if [[ "$2" == "cask" ]]; then
      echo "### Cask ###"
      xargs brew install --cask <$root/brew/cask.txt
    fi
  fi
fi

echo "### Updating dotfiles ###"
git -C $root submodule update --init

echo "### Linking configuration ###"
ln -sf $root/zsh/rc.zsh ~/.zshrc
ln -sf $root/wezterm.lua ~/.wezterm.lua
rm -rf ~/.config/ghostty
ln -sf $root/ghostty ~/.config/ghostty
ln -sf $root/zsh/zimrc.zsh ~/.zimrc
ln -sf $root/zsh/p10k.zsh ~/.p10k.zsh
ln -sf $root/tmux/tmux.conf ~/.tmux.conf
rm -rf ~/.tmux
ln -sf $root/tmux/ ~/.tmux
mkdir -p ~/.config/fish
ln -sf $root/fish/config.fish ~/.config/fish/config.fish
ln -sf $root/git/unix ~/.gitconfig
rm -rf ~/.config/git
ln -sf $root/git ~/.config/git
ln -sf $root/git/ignore ~/.gitignore
ln -sf $root/ackrc ~/.ackrc
ln -sf $root/tigrc ~/.tigrc
ln -sf $root/conan/Makefile ~/dev/conan/cci/recipes
ln -sf $root/conan/Darwin.txt ~/dev/conan/cci/recipes/Darwin.txt
ln -sf $root/conan/ios.txt ~/dev/conan/cci/recipes/ios.txt
cp $root/conan/gitignore ~/dev/conan/cci/recipes/.gitignore
