#!/bin/bash

script_path=`pwd`/$0
script_relative_path='/dotsetup'
root=${script_path%$script_relative_path};

echo "Dotfiles root: $root"

command_exists () {
  type "$1" &> /dev/null ;
}

if [[ "$OSTYPE" = linux* ]]; then
  sudo add-apt-repository -y ppa:jonathonf/vim
  sudo apt update
  echo "### Linux specific: Install Git, Vim and ZSH ###"
  sudo apt install -y git vim zsh openssh-server curl fish
fi

if [[ "$OSTYPE" = darwin* ]]; then
  command_exists brew || /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  brew tap caskroom/versions
  brew tap martindelille/tap
  xargs brew install < $root/brew.txt
  xargs brew cask install < $root/cask.txt
fi

echo "### Updating dotfiles ###"
git -C $root/.git pull

echo "### Linking configuration ###"
ln -sf $root/zsh/zshrc ~/.zshrc
ln -sf $root/zsh/zshenv ~/.zshenv
ln -sf $root/fish ~/.config/fish
ln -sf $root/gitconfig ~/.gitconfig
ln -sf $root/gitignore ~/.gitignore
ln -sf $root/vimrc ~/.vimrc
mkdir -p ~/.vim/autoload
ln -sf $root/vendors/vim-plug/plug.vim ~/.vim/autoload/plug.vim

if [[ "$OSTYPE" = darwin* ]]; then
    ln -sf $root/my.env.plist ~/Library/LaunchAgents/my.env.plist
fi

echo "### Install Vim plugin ###"
vim +PlugInstall +qall

echo "### Install Powerline font"
$root/vendors/fonts/install.sh
