export EDITOR=vim
# Oh my zsh
export DEFAULT_USER=`whoami`
#Add my custom script
export PATH=$PATH:$HOME/.dotfiles/bin
# Homebrew
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
# Coverity tools
export PATH=~/tools/cov-analysis-macosx-7.7.0.4/bin:$PATH
# Go
export GOPATH=~/dev/go
#export GOROOT=/usr/local/opt/go
export PATH=$GOROOT/libexec/bin:$GOPATH/bin:$PATH
# Node
export PATH=/usr/local/opt/node@14/bin:$PATH
# Git
export GIT_CREDENTIAL="cache --timeout=3600"
# Gisty
export GISTY_DIR=~/dev/gists
# Android utility
export PATH=~/dev/libs/android-sdk-macosx/tools:~/dev/libs/android-sdk-macosx/platform-tools:$PATH
# FFMpeg
#export PATH=$PATH:$FFMPEG_DEV_PATH/bin

# Qt
export QTVERSION=5.15.2
export QTPATH=$HOME/dev/Qt/$QTVERSION/clang_64
export PATH=$PATH:$QTPATH/bin

# IRC info
export IRCNICK=martinodelilo
export IRCSERVER=irc.freenode.net
# GPG
export GPG_TTY=$(tty)
# Other
export HOMEBREW_EDITOR=vi
export TERM="xterm-256color"
export CONAN_HOOK_ERROR_LEVEL=40

# Various alias
alias m="make"
alias j="cd ~/dev/phonations/Silcrow"
alias l="ls -lah"
alias d="cd ~/.dotfiles"
alias cci="cd ~/dev/conan/cci/recipes"
alias pbpc="pbpaste | pbcopy"
alias ip="ifconfig | grep 'inet '"
alias ccat="pygmentize -g"
alias p="pgs && say kowabounga"
alias acki="ack -i"
alias gap="ga -p"
alias x="exit"
alias xx="exit"
alias xxx="exit"
alias xxxx="exit"
#alias ls="colorls --dark --sort-dirs --report"
#alias lc="colorls --tree --dark"
alias f="find . -name"
alias lmb="lab mr b"
alias play="ffplay -autoexit"
alias ghprb="gh pr view --web"

## Sourcing OS-specific things
OS=$(uname -s); export OS
if [[ -f ~/.dotfiles/zsh/${OS}.zsh ]]; then
    if [[ ! -z $ZSHDEBUG ]]; then
        echo +++ ~/.dotfiles/zsh/${OS}.zsh
    fi
    source ~/.dotfiles/zsh/${OS}.zsh
fi

# Color

red=$'\e[1;31m'
grn=$'\e[1;32m'
blu=$'\e[1;34m'
mag=$'\e[1;35m'
cyn=$'\e[1;36m'
white=$'\e[0m'

function md {
  mkdir $1 && cd $1
}

function pdf {
  vared -p 'Output file name ? ' -c output
  gs -q -sPAPERSIZE=letter -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -sOutputFile=$output.pdf $@
}

function dfs {
  vared -p 'Application ? ' -ch app
  vared -p 'Setting ? ' -ch setting
  vared -p 'Value ? ' -ch value
  defaults write tv.lylo.$app $setting $value
  defaults read tv.lylo.$app
}
