# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#zmodload zsh/zprof

fpath=(${HOME}/.dotfiles/functions $fpath)

export ZPLUG_HOME=${HOME}/.dotfiles/vendors/zplug
source $ZPLUG_HOME/init.zsh

zplug "plugins/git", from:oh-my-zsh
zplug "plugins/osx", from:oh-my-zsh
zplug "lib/completion", from:oh-my-zsh

zplug "zsh-users/zsh-syntax-highlighting", defer:2

zplug "romkatv/powerlevel10k", as:theme

zplug load

# Uncomment the following line to disable auto-setting terminal title.
#DISABLE_AUTO_TITLE="true"

source "${HOME}/.dotfiles/zsh/iterm2_shell_integration.zsh"

export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

#zprof

[ -f $HOME/.secret ] && source $HOME/.secret ]

# To customize prompt, run `p10k configure` or edit p10k.zsh.
source ~/.dotfiles/zsh/p10k.zsh


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Make Ctrl+e accept autosuggestion
bindkey '^e' autosuggest-accept

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

setopt autocd
