# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#zmodload zsh/zprof

fpath=(${HOME}/.dotfiles/functions $fpath)

export ZPLUG_HOME=${HOME}/.dotfiles/vendors/zplug
source $ZPLUG_HOME/init.zsh

zplug "plugins/git", from:oh-my-zsh
zplug "plugins/osx", from:oh-my-zsh
zplug "lib/completion", from:oh-my-zsh

zplug "zsh-users/zsh-syntax-highlighting", defer:2
zplug "zsh-users/zsh-completions"
zplug "zsh-users/zsh-history-substring-search"

zplug "romkatv/powerlevel10k", as:theme
zplug "kutsan/zsh-system-clipboard"

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

zplug load

bindkey "^[[A" history-substring-search-up
bindkey "^[[B" history-substring-search-down

# Uncomment the following line to disable auto-setting terminal title.
#DISABLE_AUTO_TITLE="true"

source "${HOME}/.dotfiles/zsh/iterm2_shell_integration.zsh"

export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

#zprof

[ -f $HOME/.secret ] && source $HOME/.secret ]

# To customize prompt, run `p10k configure` or edit p10k.zsh.
source ~/.dotfiles/zsh/p10k.zsh


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Make Ctrl+e accept autosuggestion
bindkey '^e' autosuggest-accept

zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

export HISTSIZE=2000
export SAVEHIST=$HISTSIZE
setopt share_history
setopt hist_ignore_all_dups
setopt hist_ignore_space
setopt autocd
# Ruby / rbenv
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

# Python / pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

eval "$(pyenv init -)"

# Make sure to restart your entire logon session
# for changes to profile files to take effect.

# fshow - git commit browser
# source: https://junegunn.kr/2015/03/browsing-git-commits-with-fzf
fshow() {
  local out sha q
  while out=$(
      git log --graph --color=always \
          --format="%C(auto)%h%d %s %C(black)%C(bold)%cr" "$@" |
      fzf --ansi --multi --no-sort --reverse --query="$q" --print-query); do
    q=$(head -1 <<< "$out")
    while read sha; do
      git show --color=always $sha | less -R
    done < <(sed '1d;s/^[^a-z0-9]*//;/^$/d' <<< "$out" | awk '{print $1}')
  done
}
